apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: s1-dep 
spec: 
  replicas: 1 
  selector: 
    matchlables: 
      app: blue-app 
  template: 
    metadata: 
      labels: 
          
    spec: 
      containers: 
      - name: c1 
        image: sujithdevops/img1:blue 
        ports: 
        - containerPort: 80 

--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: blue-svc   
spec: 
  type: nodePort 
  selector: 
    app: blue-app 
  ports: 
  - port: 80 
    targetPort: 80 

--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: su-ingress
  annotations: 
    kubernetes.io/ingress.class: "gce"     
spec: 
  rules: 
  - http: 
    paths: 
    - pathType: Prefix 
      path: "/" 
      backend: 
        service: 
          name: blue-svc
        port: 
          number: 80
#------------------------------------------------------------------------------------------------------  
#------------------------------------------------------------------------------------------------------
#------------------------------------------------------------------------------------------------------

--- 
apiVersion: networking.k8s.io/v1 