apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: su-deployment2
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: backend
  template: 
    metadata: 
      labels: 
      app: backend 
    spec: 
      containers: 
      - name: c3
        image: busybox 
        command: ['sh','-c','echo I have enrolled for $COURSENAME and my password is $MYPASSWORD; sleep 3600; done']
        env: 
        - name: COURSENAME 
          valueFrom: 
            configMapKeyRef:  
              name: my-config 
              key: course
        - name: MYPASSWORD 
          valueFrom: 
            secretKeyRef: 
              name: db-secret 
              key: password 

#  Attaching the volumes to the ConfigMap : 
---
apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: su-dep3
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: front-end 
  template: 
    metadata: 
      labels: 
        app: front-end  
    spec: 
      volumes: 
      - name: sujith-vol1 
        configMap: 
          name: my-config
      containers: 
      - name: c56 
        image: busybox
        command: ["sh", "-c", "echo cat /config/name  /config/course && sleep 3600"]
        volumeMounts: 
        - name: sujith-vol1
          mountPath: "/config"          
